# Generated by Django 4.1.7 on 2023-03-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_book_options_alter_book_name_alter_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(
                default="a", max_length=255, verbose_name="Автор"
            ),
            preserve_default=False,
        ),
    ]
