# Generated by Django 4.1.7 on 2023-03-01 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_book_author_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Книги", "verbose_name_plural": "Книги"},
        ),
    ]
