# Generated by Django 4.1.7 on 2023-03-04 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_book_readers_alter_book_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
    ]
